server:
  port: 7100
  tomcat:
    additional-tld-skip-patterns: "*.jar"

spring: 
  mail: 
    properties:
      mail:
       smtp:
        auth: true
        timeout: 5000
        starttls:
          enable: true 
    password: spldhctwcwpvubmm
    username: ijhghji
    port: 587
    host: smtp.gmail.com
  web:
    resources:
      static-locations: /resources/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

      #location: C:/Users/bitcamp/git/seulmeal/seulmeal/src/main/resources/attachments/
#location: /src/main/resources/attachments/
      location: C:/Users/GHM/git/seulmeal/seulmeal/src/main/webapp/resources/attachments/profile_image
      #location: C:/Users/bitcamp/git/seulmeal/seulmeal/src/main/resources/attachments/
  datasource:
    url: jdbc:log4jdbc:oracle:thin:@db202204092247_high?TNS_ADMIN=./oracleWallet/Wallet_DB202204092247

    #url: jdbc:log4jdbc:oracle:thin:@db202204092247_high?TNS_ADMIN=D:/oracle/Wallet_DB202204092247

    #url: jdbc:log4jdbc:oracle:thin:@db202204092247_high?TNS_ADMIN=C:/Util/Wallet_DB202204092247
    username: admin
    password: Vywjdans!234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  mvc: 
    static-path-pattern: /resources/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
mybatis:
  type-aliases-package: shop.seulmeal.service.domain
  mapper-locations: shop.seulmeal.service.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

